# Generated by Django 4.2.2 on 2023-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
