# Generated by Django 4.2.2 on 2023-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0004_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_image2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mybg/')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Background_image3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mybg/')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
            ],
        ),
    ]
