# Generated by Django 4.1.3 on 2023-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0005_background_image2_background_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='history_images/')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
