# Generated by Django 4.1.3 on 2023-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0006_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalSurgeryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='surgery_images/')),
            ],
        ),
    ]
