# Generated by Django 4.1.3 on 2023-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0007_dentalsurgerystep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalsurgerystep',
            name='image',
            field=models.ImageField(null=True, upload_to='surgery_images/'),
        ),
        migrations.AlterField(
            model_name='dentalsurgerystep',
            name='step_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dentalsurgerystep',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(null=True, upload_to='history_images/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
